name: Windows-CMake
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    name: Windows compilation
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install GLFW3
        run: vcpkg install glfw3
      - name: Build
        run: set CMAKE_TOOLCHAIN_FILE="C:\\Program Files\vcpkg\scripts\buildsystems\vcpkg.cmake" && .\scripts\build.bat
