name: Windows-CMake
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    name: Windows compilation
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: build
        run: .\scripts\build.bat
